spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?useSSL=false&useUnicode=true&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

dubbo:
  application:
    name: local_service
  protocol:
    name: dubbo
    port: -1
    server: netty
    client: netty
    charset: UTF-8
    threadpool: fixed
    threads: 500
    queues: 0
    buffer: 8192
    accepts: 0
    payload: 8388608
  registry:
    address: localhost:2181
    protocol: zookeeper