spring:
  main:
    allow-bean-definition-overriding: true
  jms:
    pub-sub-domain: true
  activemq:
    broker-url: tcp://0.0.0.0:61616
    user: admin
    password: admin
    pool:
      enabled: true
      max-connections: 100
