spring:
  kafka:
    bootstrap-servers: localhost:19092, localhost:19093, localhost:19094
    producer:
      retries: 1
      batch-size: 16384
      buffer-memory: 1024000
      properties:
        linger.ms: 1
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 100
      group-id: group
#    template:
#      default-topic: group
