spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jdbc_demo?useUnicode=true&serverTimezone=GMT%2B8
    username: root
    password: root
    hikari:
      max-lifetime: 30000
      maximum-pool-size: 14
      minimum-idle: 4